/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dashboard.Manager.Menu;

import Controller.Kereta.kelasController;
import Controller.Kereta.keretaController;
import Model.Kelas;
import Model.Kereta;
import java.awt.CardLayout;
import java.awt.Color;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Ouka
 */

public class keretaCardMenu extends javax.swing.JPanel {
    /**
     * Creates new form jadwalCardMenu
     */
    private Kelas kelas;
    private kelasController controller;
    private DefaultTableModel tbModel;
    private int pos;
    
    private Kereta kereta;
    private keretaController controler;
    private DefaultTableModel tbModelKereta;
    
    CardLayout menuTab;
    public keretaCardMenu() throws SQLException {
        initComponents();
        btnUpdateKelas.setEnabled(false);
        btnDeleteKelas.setEnabled(false);
        controller = new kelasController();
        tbModel = (DefaultTableModel) tbKelas.getModel();
        btnInsertKelas.setFocusPainted(false);
        btnUpdateKelas.setFocusPainted(false);
        btnDeleteKelas.setFocusPainted(false);
        btnResetKelas.setFocusPainted(false);
        menuTab = (CardLayout) contentBodyMenuCard.getLayout();
        menuTab.show(contentBodyMenuCard, "card1");
        show_data_to_table();
        AutoCompleteDecorator.decorate(txtPilihKelas);
        
        btnInsert.setFocusPainted(false);
        btnUpdate.setFocusPainted(false);
        btnDelete.setFocusPainted(false);
        btnReset.setFocusPainted(false);
        btnDetail.setFocusPainted(false);
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
        controler = new keretaController();
        tbModelKereta = (DefaultTableModel) tbKereta.getModel();
        show_data_to_table_kereta();
    }
    
    public void show_data_to_table() throws SQLException{
        List<Kelas> keArr = controller.selectAll();
        txtPilihKelas.removeAllItems();
        tbModel.setRowCount(0);
        Object[] kolom = new Object[4];
        for (int i = 0; i < keArr.size(); i++) {
            kolom[0] = i+1;
            kolom[1] = keArr.get(i).getId_kelas();
            kolom[2] = keArr.get(i).getNama();
            kolom[3] = keArr.get(i).getKeterangan();
             
            tbModel.addRow(kolom);
            txtPilihKelas.addItem(keArr.get(i).getId_kelas());
         }
    }
    
    public void show_data_to_table_kereta() throws SQLException{
        List<Kereta> keArr = controler.selectAll();
        tbModelKereta.setRowCount(0);
        Object[] kolom = new Object[5];
        for (int i = 0; i < keArr.size(); i++) {
            kolom[0] = i+1;
            kolom[1] = keArr.get(i).getId_kereta();
            kolom[2] = keArr.get(i).getNama_Kereta();
            kolom[3] = keArr.get(i).getId_kelas();
            kolom[4] = keArr.get(i).getGerbong();
             
            tbModelKereta.addRow(kolom);
         }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bodyMenuTab = new javax.swing.JPanel();
        btnMenuKereta = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnMenuKelas = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        contentBodyMenuCard = new javax.swing.JPanel();
        contentCardKereta = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbKereta = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtIdkereta = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtNama = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        txtPilihKelas = new javax.swing.JComboBox<>();
        txtGerbong = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnDetail = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btnFirst = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnPrev = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnNext = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnLast = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        contentCardKelas = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbKelas = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txtIdkelas = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        txtNamakelas = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        txtKeterangankelas = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        btnInsertKelas = new javax.swing.JButton();
        btnUpdateKelas = new javax.swing.JButton();
        btnDeleteKelas = new javax.swing.JButton();
        btnResetKelas = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        btnFirstKelas = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        btnPrevKelas = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        btnNextKelas = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        btnLastKelas = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 30, 84));
        setPreferredSize(new java.awt.Dimension(1150, 660));

        headerMenu.setBackground(new java.awt.Color(227, 237, 240));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Management Kereta Api Sederhana");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Daftar Petugas");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Home>Daftar Petugas");

        javax.swing.GroupLayout headerMenuLayout = new javax.swing.GroupLayout(headerMenu);
        headerMenu.setLayout(headerMenuLayout);
        headerMenuLayout.setHorizontalGroup(
            headerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerMenuLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(headerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(843, Short.MAX_VALUE))
        );
        headerMenuLayout.setVerticalGroup(
            headerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerMenuLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        bodyMenuTab.setBackground(new java.awt.Color(0, 42, 113));
        bodyMenuTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMenuKereta.setBackground(new java.awt.Color(0, 42, 113));
        btnMenuKereta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuKereta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuKeretaMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Kereta");

        javax.swing.GroupLayout btnMenuKeretaLayout = new javax.swing.GroupLayout(btnMenuKereta);
        btnMenuKereta.setLayout(btnMenuKeretaLayout);
        btnMenuKeretaLayout.setHorizontalGroup(
            btnMenuKeretaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btnMenuKeretaLayout.setVerticalGroup(
            btnMenuKeretaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bodyMenuTab.add(btnMenuKereta, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, -1, -1));

        btnMenuKelas.setBackground(new java.awt.Color(0, 42, 113));
        btnMenuKelas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuKelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuKelasMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Kelas");

        javax.swing.GroupLayout btnMenuKelasLayout = new javax.swing.GroupLayout(btnMenuKelas);
        btnMenuKelas.setLayout(btnMenuKelasLayout);
        btnMenuKelasLayout.setHorizontalGroup(
            btnMenuKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btnMenuKelasLayout.setVerticalGroup(
            btnMenuKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bodyMenuTab.add(btnMenuKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, -1, -1));

        contentBodyMenuCard.setBackground(new java.awt.Color(0, 30, 84));
        contentBodyMenuCard.setLayout(new java.awt.CardLayout());

        contentCardKereta.setBackground(new java.awt.Color(0, 30, 84));

        jPanel5.setBackground(new java.awt.Color(0, 42, 113));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbKereta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "ID Kereta", "Nama", "Kelas", "Jumlah Gerbong"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbKereta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbKeretaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbKereta);
        if (tbKereta.getColumnModel().getColumnCount() > 0) {
            tbKereta.getColumnModel().getColumn(0).setResizable(false);
            tbKereta.getColumnModel().getColumn(0).setPreferredWidth(30);
            tbKereta.getColumnModel().getColumn(1).setPreferredWidth(200);
            tbKereta.getColumnModel().getColumn(2).setPreferredWidth(200);
            tbKereta.getColumnModel().getColumn(3).setPreferredWidth(200);
            tbKereta.getColumnModel().getColumn(4).setPreferredWidth(200);
        }

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 750, 340));

        jPanel6.setBackground(new java.awt.Color(0, 42, 113));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel17.setBackground(new java.awt.Color(0, 42, 113));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ID Kereta");

        txtIdkereta.setBackground(new java.awt.Color(0, 42, 113));
        txtIdkereta.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtIdkereta.setForeground(new java.awt.Color(255, 255, 255));
        txtIdkereta.setBorder(null);
        txtIdkereta.setCaretColor(new java.awt.Color(255, 0, 0));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        txtNama.setBackground(new java.awt.Color(0, 42, 113));
        txtNama.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtNama.setForeground(new java.awt.Color(255, 255, 255));
        txtNama.setBorder(null);
        txtNama.setCaretColor(new java.awt.Color(255, 0, 0));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Nama");

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Kelas");

        txtPilihKelas.setBackground(new java.awt.Color(0, 74, 163));
        txtPilihKelas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPilihKelas.setBorder(null);
        txtPilihKelas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtPilihKelas.setFocusable(false);

        txtGerbong.setBackground(new java.awt.Color(0, 42, 113));
        txtGerbong.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtGerbong.setForeground(new java.awt.Color(255, 255, 255));
        txtGerbong.setBorder(null);
        txtGerbong.setCaretColor(new java.awt.Color(255, 0, 0));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Gerbong");

        btnInsert.setBackground(new java.awt.Color(0, 74, 163));
        btnInsert.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnInsert.setForeground(new java.awt.Color(255, 255, 255));
        btnInsert.setText("Insert");
        btnInsert.setBorder(null);
        btnInsert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInsert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInsertMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInsertMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnInsertMouseReleased(evt);
            }
        });
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(0, 74, 163));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.setBorder(null);
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdateMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnUpdateMouseReleased(evt);
            }
        });
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(0, 74, 163));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.setBorder(null);
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnDeleteMouseReleased(evt);
            }
        });
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(0, 74, 163));
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Reset");
        btnReset.setBorder(null);
        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnResetMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnResetMouseReleased(evt);
            }
        });
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnDetail.setBackground(new java.awt.Color(0, 74, 163));
        btnDetail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDetail.setForeground(new java.awt.Color(255, 255, 255));
        btnDetail.setText("Detail");
        btnDetail.setBorder(null);
        btnDetail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDetailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDetailMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnDetailMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNama, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPilihKelas, javax.swing.GroupLayout.Alignment.TRAILING, 0, 202, Short.MAX_VALUE)
                            .addComponent(txtIdkereta)))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtGerbong, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                            .addComponent(jSeparator7)))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnDetail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel17Layout.createSequentialGroup()
                                .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtIdkereta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtPilihKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtGerbong, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jPanel6.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 280, 390));

        jPanel7.setBackground(new java.awt.Color(0, 42, 113));
        jPanel7.setPreferredSize(new java.awt.Dimension(0, 35));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFirst.setBackground(new java.awt.Color(0, 74, 163));
        btnFirst.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFirst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFirstMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFirstMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFirstMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnFirstMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnFirstMouseReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("First");

        javax.swing.GroupLayout btnFirstLayout = new javax.swing.GroupLayout(btnFirst);
        btnFirst.setLayout(btnFirstLayout);
        btnFirstLayout.setHorizontalGroup(
            btnFirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btnFirstLayout.setVerticalGroup(
            btnFirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel7.add(btnFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, -1));

        btnPrev.setBackground(new java.awt.Color(0, 74, 163));
        btnPrev.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrevMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPrevMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPrevMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPrevMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPrevMouseReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Prev");

        javax.swing.GroupLayout btnPrevLayout = new javax.swing.GroupLayout(btnPrev);
        btnPrev.setLayout(btnPrevLayout);
        btnPrevLayout.setHorizontalGroup(
            btnPrevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btnPrevLayout.setVerticalGroup(
            btnPrevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel7.add(btnPrev, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, -1, -1));

        btnNext.setBackground(new java.awt.Color(0, 74, 163));
        btnNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNextMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNextMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnNextMouseReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Next");

        javax.swing.GroupLayout btnNextLayout = new javax.swing.GroupLayout(btnNext);
        btnNext.setLayout(btnNextLayout);
        btnNextLayout.setHorizontalGroup(
            btnNextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btnNextLayout.setVerticalGroup(
            btnNextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jPanel7.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, -1, -1));

        btnLast.setBackground(new java.awt.Color(0, 74, 163));
        btnLast.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLast.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLastMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLastMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLastMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLastMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLastMouseReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Last");

        javax.swing.GroupLayout btnLastLayout = new javax.swing.GroupLayout(btnLast);
        btnLast.setLayout(btnLastLayout);
        btnLastLayout.setHorizontalGroup(
            btnLastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btnLastLayout.setVerticalGroup(
            btnLastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel7.add(btnLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, -1, -1));

        javax.swing.GroupLayout contentCardKeretaLayout = new javax.swing.GroupLayout(contentCardKereta);
        contentCardKereta.setLayout(contentCardKeretaLayout);
        contentCardKeretaLayout.setHorizontalGroup(
            contentCardKeretaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentCardKeretaLayout.createSequentialGroup()
                .addGroup(contentCardKeretaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        contentCardKeretaLayout.setVerticalGroup(
            contentCardKeretaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentCardKeretaLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        contentBodyMenuCard.add(contentCardKereta, "card1");

        contentCardKelas.setBackground(new java.awt.Color(0, 30, 84));

        jPanel8.setBackground(new java.awt.Color(0, 42, 113));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbKelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "ID Kelas", "Nama Kelas", "Keterangan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbKelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbKelasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbKelas);
        if (tbKelas.getColumnModel().getColumnCount() > 0) {
            tbKelas.getColumnModel().getColumn(0).setResizable(false);
            tbKelas.getColumnModel().getColumn(0).setPreferredWidth(30);
            tbKelas.getColumnModel().getColumn(1).setPreferredWidth(200);
            tbKelas.getColumnModel().getColumn(2).setPreferredWidth(200);
            tbKelas.getColumnModel().getColumn(3).setPreferredWidth(200);
        }

        jPanel8.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 750, 340));

        jPanel9.setBackground(new java.awt.Color(0, 42, 113));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel18.setBackground(new java.awt.Color(0, 42, 113));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("ID Kelas");

        txtIdkelas.setBackground(new java.awt.Color(0, 42, 113));
        txtIdkelas.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtIdkelas.setForeground(new java.awt.Color(255, 255, 255));
        txtIdkelas.setBorder(null);
        txtIdkelas.setCaretColor(new java.awt.Color(255, 0, 0));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));

        txtNamakelas.setBackground(new java.awt.Color(0, 42, 113));
        txtNamakelas.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtNamakelas.setForeground(new java.awt.Color(255, 255, 255));
        txtNamakelas.setBorder(null);
        txtNamakelas.setCaretColor(new java.awt.Color(255, 0, 0));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Nama");

        txtKeterangankelas.setBackground(new java.awt.Color(0, 42, 113));
        txtKeterangankelas.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtKeterangankelas.setForeground(new java.awt.Color(255, 255, 255));
        txtKeterangankelas.setBorder(null);
        txtKeterangankelas.setCaretColor(new java.awt.Color(255, 0, 0));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Keterangan");

        btnInsertKelas.setBackground(new java.awt.Color(0, 74, 163));
        btnInsertKelas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnInsertKelas.setForeground(new java.awt.Color(255, 255, 255));
        btnInsertKelas.setText("Insert");
        btnInsertKelas.setBorder(null);
        btnInsertKelas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInsertKelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInsertKelasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInsertKelasMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnInsertKelasMouseReleased(evt);
            }
        });
        btnInsertKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertKelasActionPerformed(evt);
            }
        });

        btnUpdateKelas.setBackground(new java.awt.Color(0, 74, 163));
        btnUpdateKelas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdateKelas.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateKelas.setText("Update");
        btnUpdateKelas.setBorder(null);
        btnUpdateKelas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdateKelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdateKelasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdateKelasMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnUpdateKelasMouseReleased(evt);
            }
        });
        btnUpdateKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateKelasActionPerformed(evt);
            }
        });

        btnDeleteKelas.setBackground(new java.awt.Color(0, 74, 163));
        btnDeleteKelas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDeleteKelas.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteKelas.setText("Delete");
        btnDeleteKelas.setBorder(null);
        btnDeleteKelas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeleteKelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteKelasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteKelasMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnDeleteKelasMouseReleased(evt);
            }
        });
        btnDeleteKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteKelasActionPerformed(evt);
            }
        });

        btnResetKelas.setBackground(new java.awt.Color(0, 74, 163));
        btnResetKelas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnResetKelas.setForeground(new java.awt.Color(255, 255, 255));
        btnResetKelas.setText("Reset");
        btnResetKelas.setBorder(null);
        btnResetKelas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResetKelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnResetKelasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnResetKelasMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnResetKelasMouseReleased(evt);
            }
        });
        btnResetKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetKelasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtKeterangankelas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNamakelas, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtIdkelas, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator6)))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(btnInsertKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnResetKelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(txtIdkelas, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtNamakelas, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtKeterangankelas, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResetKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel9.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 280, 390));

        jPanel10.setBackground(new java.awt.Color(0, 42, 113));
        jPanel10.setPreferredSize(new java.awt.Dimension(0, 35));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFirstKelas.setBackground(new java.awt.Color(0, 74, 163));
        btnFirstKelas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFirstKelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFirstKelasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFirstKelasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFirstKelasMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnFirstKelasMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnFirstKelasMouseReleased(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("First");

        javax.swing.GroupLayout btnFirstKelasLayout = new javax.swing.GroupLayout(btnFirstKelas);
        btnFirstKelas.setLayout(btnFirstKelasLayout);
        btnFirstKelasLayout.setHorizontalGroup(
            btnFirstKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btnFirstKelasLayout.setVerticalGroup(
            btnFirstKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel10.add(btnFirstKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, -1));

        btnPrevKelas.setBackground(new java.awt.Color(0, 74, 163));
        btnPrevKelas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrevKelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrevKelasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPrevKelasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPrevKelasMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPrevKelasMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPrevKelasMouseReleased(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Prev");

        javax.swing.GroupLayout btnPrevKelasLayout = new javax.swing.GroupLayout(btnPrevKelas);
        btnPrevKelas.setLayout(btnPrevKelasLayout);
        btnPrevKelasLayout.setHorizontalGroup(
            btnPrevKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btnPrevKelasLayout.setVerticalGroup(
            btnPrevKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel10.add(btnPrevKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, -1, -1));

        btnNextKelas.setBackground(new java.awt.Color(0, 74, 163));
        btnNextKelas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNextKelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNextKelasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNextKelasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNextKelasMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNextKelasMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnNextKelasMouseReleased(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Next");

        javax.swing.GroupLayout btnNextKelasLayout = new javax.swing.GroupLayout(btnNextKelas);
        btnNextKelas.setLayout(btnNextKelasLayout);
        btnNextKelasLayout.setHorizontalGroup(
            btnNextKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btnNextKelasLayout.setVerticalGroup(
            btnNextKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jPanel10.add(btnNextKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, -1, -1));

        btnLastKelas.setBackground(new java.awt.Color(0, 74, 163));
        btnLastKelas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLastKelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLastKelasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLastKelasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLastKelasMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLastKelasMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLastKelasMouseReleased(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Last");

        javax.swing.GroupLayout btnLastKelasLayout = new javax.swing.GroupLayout(btnLastKelas);
        btnLastKelas.setLayout(btnLastKelasLayout);
        btnLastKelasLayout.setHorizontalGroup(
            btnLastKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btnLastKelasLayout.setVerticalGroup(
            btnLastKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel10.add(btnLastKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, -1, -1));

        javax.swing.GroupLayout contentCardKelasLayout = new javax.swing.GroupLayout(contentCardKelas);
        contentCardKelas.setLayout(contentCardKelasLayout);
        contentCardKelasLayout.setHorizontalGroup(
            contentCardKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentCardKelasLayout.createSequentialGroup()
                .addGroup(contentCardKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        contentCardKelasLayout.setVerticalGroup(
            contentCardKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentCardKelasLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        contentBodyMenuCard.add(contentCardKelas, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bodyMenuTab, javax.swing.GroupLayout.DEFAULT_SIZE, 1078, Short.MAX_VALUE)
                    .addComponent(contentBodyMenuCard, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(bodyMenuTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(contentBodyMenuCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnFirstMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFirstMouseEntered
        btnFirst.setBackground(new Color(47, 71, 194));
    }//GEN-LAST:event_btnFirstMouseEntered

    private void btnFirstMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFirstMouseExited
        btnFirst.setBackground(new Color(0,74,163));
    }//GEN-LAST:event_btnFirstMouseExited

    private void btnFirstMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFirstMousePressed
        btnFirst.setBackground(new Color(6, 58, 120));// TODO add your handling code here:
    }//GEN-LAST:event_btnFirstMousePressed

    private void btnFirstMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFirstMouseReleased
        btnFirst.setBackground(new Color(0,74,163));
    }//GEN-LAST:event_btnFirstMouseReleased

    private void btnPrevMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrevMouseEntered
        btnPrev.setBackground(new Color(47, 71, 194));
    }//GEN-LAST:event_btnPrevMouseEntered

    private void btnPrevMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrevMouseExited
        btnPrev.setBackground(new Color(0,74,163));
    }//GEN-LAST:event_btnPrevMouseExited

    private void btnPrevMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrevMousePressed
        btnPrev.setBackground(new Color(6, 58, 120));
    }//GEN-LAST:event_btnPrevMousePressed

    private void btnPrevMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrevMouseReleased
        btnPrev.setBackground(new Color(0,74,163));
    }//GEN-LAST:event_btnPrevMouseReleased

    private void btnNextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseEntered
        btnNext.setBackground(new Color(47, 71, 194));
    }//GEN-LAST:event_btnNextMouseEntered

    private void btnNextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseExited
        btnNext.setBackground(new Color(0,74,163));
    }//GEN-LAST:event_btnNextMouseExited

    private void btnNextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMousePressed
        btnNext.setBackground(new Color(6, 58, 120));
    }//GEN-LAST:event_btnNextMousePressed

    private void btnNextMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseReleased
        btnNext.setBackground(new Color(0,74,163));
    }//GEN-LAST:event_btnNextMouseReleased

    private void btnLastMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLastMouseEntered
        btnLast.setBackground(new Color(47, 71, 194));
    }//GEN-LAST:event_btnLastMouseEntered

    private void btnLastMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLastMouseExited
        btnLast.setBackground(new Color(0,74,163));
    }//GEN-LAST:event_btnLastMouseExited

    private void btnLastMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLastMousePressed
        btnLast.setBackground(new Color(6, 58, 120));
    }//GEN-LAST:event_btnLastMousePressed

    private void btnLastMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLastMouseReleased
        btnLast.setBackground(new Color(0,74,163));
    }//GEN-LAST:event_btnLastMouseReleased

    private void btnMenuKeretaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuKeretaMouseClicked
        btnMenuKereta.setBackground(new Color(0,74,163));
        btnMenuKelas.setBackground(new Color(0,42,113));
        menuTab.show(contentBodyMenuCard, "card1");
    }//GEN-LAST:event_btnMenuKeretaMouseClicked

    private void btnMenuKelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuKelasMouseClicked
        btnMenuKereta.setBackground(new Color(0,42,113));
        btnMenuKelas.setBackground(new Color(0,74,163));
        menuTab.show(contentBodyMenuCard, "card2");
    }//GEN-LAST:event_btnMenuKelasMouseClicked

    private void btnFirstKelasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFirstKelasMouseEntered
        btnFirstKelas.setBackground(new Color(47, 71, 194));
    }//GEN-LAST:event_btnFirstKelasMouseEntered

    private void btnFirstKelasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFirstKelasMouseExited
        btnFirstKelas.setBackground(new Color(0,74,163));
    }//GEN-LAST:event_btnFirstKelasMouseExited

    private void btnFirstKelasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFirstKelasMousePressed
        btnFirstKelas.setBackground(new Color(6, 58, 120));
    }//GEN-LAST:event_btnFirstKelasMousePressed

    private void btnFirstKelasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFirstKelasMouseReleased
        btnFirstKelas.setBackground(new Color(0,74,163));
    }//GEN-LAST:event_btnFirstKelasMouseReleased

    private void btnPrevKelasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrevKelasMouseEntered
        btnPrevKelas.setBackground(new Color(47, 71, 194));
    }//GEN-LAST:event_btnPrevKelasMouseEntered

    private void btnPrevKelasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrevKelasMouseExited
        btnPrevKelas.setBackground(new Color(0,74,163));
    }//GEN-LAST:event_btnPrevKelasMouseExited

    private void btnPrevKelasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrevKelasMousePressed
        btnPrevKelas.setBackground(new Color(6, 58, 120));
    }//GEN-LAST:event_btnPrevKelasMousePressed

    private void btnPrevKelasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrevKelasMouseReleased
        btnPrevKelas.setBackground(new Color(0,74,163));
    }//GEN-LAST:event_btnPrevKelasMouseReleased

    private void btnNextKelasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextKelasMouseEntered
        btnNextKelas.setBackground(new Color(47, 71, 194));
    }//GEN-LAST:event_btnNextKelasMouseEntered

    private void btnNextKelasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextKelasMouseExited
        btnNextKelas.setBackground(new Color(0,74,163));
    }//GEN-LAST:event_btnNextKelasMouseExited

    private void btnNextKelasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextKelasMousePressed
        btnNextKelas.setBackground(new Color(6, 58, 120));
    }//GEN-LAST:event_btnNextKelasMousePressed

    private void btnNextKelasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextKelasMouseReleased
        btnNextKelas.setBackground(new Color(0,74,163));
    }//GEN-LAST:event_btnNextKelasMouseReleased

    private void btnLastKelasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLastKelasMouseEntered
        btnLastKelas.setBackground(new Color(47, 71, 194));
    }//GEN-LAST:event_btnLastKelasMouseEntered

    private void btnLastKelasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLastKelasMouseExited
        btnLastKelas.setBackground(new Color(0,74,163));
    }//GEN-LAST:event_btnLastKelasMouseExited

    private void btnLastKelasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLastKelasMousePressed
        btnLastKelas.setBackground(new Color(6, 58, 120));
    }//GEN-LAST:event_btnLastKelasMousePressed

    private void btnLastKelasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLastKelasMouseReleased
        btnLastKelas.setBackground(new Color(0,74,163));
    }//GEN-LAST:event_btnLastKelasMouseReleased

    private void btnInsertKelasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertKelasMouseEntered
        btnInsertKelas.setBackground(new Color(47, 71, 194));
    }//GEN-LAST:event_btnInsertKelasMouseEntered

    private void btnInsertKelasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertKelasMouseExited
        btnInsertKelas.setBackground(new Color(0,74,163));
    }//GEN-LAST:event_btnInsertKelasMouseExited

    private void btnInsertKelasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertKelasMouseReleased
        btnInsertKelas.setBackground(new Color(0,74,163));
    }//GEN-LAST:event_btnInsertKelasMouseReleased

    private void btnUpdateKelasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateKelasMouseEntered
        btnUpdateKelas.setBackground(new Color(47, 71, 194));
    }//GEN-LAST:event_btnUpdateKelasMouseEntered

    private void btnUpdateKelasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateKelasMouseExited
        btnUpdateKelas.setBackground(new Color(0,74,163));
    }//GEN-LAST:event_btnUpdateKelasMouseExited

    private void btnUpdateKelasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateKelasMouseReleased
        btnUpdateKelas.setBackground(new Color(0,74,163));
    }//GEN-LAST:event_btnUpdateKelasMouseReleased

    private void btnDeleteKelasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteKelasMouseEntered
        btnDeleteKelas.setBackground(new Color(47, 71, 194));
    }//GEN-LAST:event_btnDeleteKelasMouseEntered

    private void btnDeleteKelasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteKelasMouseExited
        btnDeleteKelas.setBackground(new Color(0,74,163));
    }//GEN-LAST:event_btnDeleteKelasMouseExited

    private void btnDeleteKelasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteKelasMouseReleased
        btnDeleteKelas.setBackground(new Color(0,74,163));
    }//GEN-LAST:event_btnDeleteKelasMouseReleased

    private void btnResetKelasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetKelasMouseEntered
        btnResetKelas.setBackground(new Color(47, 71, 194));
    }//GEN-LAST:event_btnResetKelasMouseEntered

    private void btnResetKelasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetKelasMouseExited
        btnResetKelas.setBackground(new Color(0,74,163));
    }//GEN-LAST:event_btnResetKelasMouseExited

    private void btnResetKelasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetKelasMouseReleased
        btnResetKelas.setBackground(new Color(0,74,163));
    }//GEN-LAST:event_btnResetKelasMouseReleased

    private void tbKelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKelasMouseClicked
        if(tbKelas.getSelectionModel().isSelectionEmpty()){
            System.out.println("null");
        } else{
            btnUpdateKelas.setEnabled(true);
            btnDeleteKelas.setEnabled(true);
            btnInsertKelas.setEnabled(false);
            txtIdkelas.setEditable(false);
            int index = tbKelas.getSelectedRow();
            show_item_in_form(index);
        }
    }//GEN-LAST:event_tbKelasMouseClicked

    private void btnInsertKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertKelasActionPerformed
        if(cekEmpty()){
            JOptionPane.showMessageDialog(this, "One or more Fields are empty!");
        } else{
            kelas = new Kelas();
            kelas.setId_kelas(txtIdkelas.getText());
            kelas.setNama(txtNamakelas.getText());
            kelas.setKeterangan(txtKeterangankelas.getText());
            try {
                controller.insertRecord(kelas);
                show_data_to_table();
                clearFields();
            } catch (SQLException ex) {
                Logger.getLogger(petugasCardMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnInsertKelasActionPerformed

    private void btnUpdateKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateKelasActionPerformed
        if(cekEmpty()){
            JOptionPane.showMessageDialog(this, "One or more Fields are empty!");
        } else{
            kelas = new Kelas();
            kelas.setId_kelas(txtIdkelas.getText());
            kelas.setNama(txtNamakelas.getText());
            kelas.setKeterangan(txtKeterangankelas.getText());
            try {
                controller.updateRecord(kelas);
                show_data_to_table();
                clearFields();
            } catch (SQLException ex) {
                Logger.getLogger(petugasCardMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnUpdateKelasActionPerformed

    private void btnDeleteKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteKelasActionPerformed
        int result = JOptionPane.showConfirmDialog(null, 
            "Hapus data masinis "+ txtIdkelas.getText() +"?",null, JOptionPane.YES_NO_OPTION);
                if(result == JOptionPane.YES_OPTION) {
                    try {
                        controller.deleteRecord(txtIdkelas.getText());
                        show_data_to_table();
                        clearFields();
                    } catch (SQLException ex) {
                        Logger.getLogger(petugasCardMenu.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else{
                    System.out.println("Abort!");
                }
    }//GEN-LAST:event_btnDeleteKelasActionPerformed

    private void btnResetKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetKelasActionPerformed
        clearFields();
    }//GEN-LAST:event_btnResetKelasActionPerformed

    private void btnFirstKelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFirstKelasMouseClicked
        pos = 0;
        show_item_in_form(pos);
        tbKelas.setRowSelectionInterval(pos, pos);
        txtIdkelas.setEditable(false);
        btnUpdateKelas.setEnabled(true);
        btnDeleteKelas.setEnabled(true);
        btnInsertKelas.setEnabled(false);
    }//GEN-LAST:event_btnFirstKelasMouseClicked

    private void btnPrevKelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrevKelasMouseClicked
        if(tbKelas.getSelectionModel().isSelectionEmpty()){
            tbKelas.setRowSelectionInterval(0, 0);
        } else{
            pos = tbKelas.getSelectedRow();
            pos--;
            if(pos < 0){
                pos = 0;
            }
            tbKelas.setRowSelectionInterval(pos, pos);
        }
        show_item_in_form(pos);
        tbKelas.setRowSelectionInterval(pos, pos);
        txtIdkelas.setEditable(false);
        btnUpdateKelas.setEnabled(true);
        btnDeleteKelas.setEnabled(true);
        btnInsertKelas.setEnabled(false);
    }//GEN-LAST:event_btnPrevKelasMouseClicked

    private void btnNextKelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextKelasMouseClicked
        if(tbKelas.getSelectionModel().isSelectionEmpty()){
            tbKelas.setRowSelectionInterval(0, 0);
        } else{
            pos = tbKelas.getSelectedRow();
            pos++;
            if(pos >= tbKelas.getRowCount()){
                pos = tbKelas.getRowCount()-1;
            }
            tbKelas.setRowSelectionInterval(pos, pos);
        }
        show_item_in_form(pos);
        tbKelas.setRowSelectionInterval(pos, pos);
        txtIdkelas.setEditable(false);
        btnUpdateKelas.setEnabled(true);
        btnDeleteKelas.setEnabled(true);
        btnInsertKelas.setEnabled(false);
    }//GEN-LAST:event_btnNextKelasMouseClicked

    private void btnLastKelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLastKelasMouseClicked
        pos = tbKelas.getRowCount()-1;
        tbKelas.setRowSelectionInterval(pos, pos);
        show_item_in_form(pos);
        txtIdkelas.setEditable(false);
        btnUpdateKelas.setEnabled(true);
        btnDeleteKelas.setEnabled(true);
        btnInsertKelas.setEnabled(false);
    }//GEN-LAST:event_btnLastKelasMouseClicked

    private void btnInsertMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertMouseEntered
        btnInsert.setBackground(new Color(47, 71, 194));
    }//GEN-LAST:event_btnInsertMouseEntered

    private void btnInsertMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertMouseExited
        btnInsert.setBackground(new Color(0,74,163));
    }//GEN-LAST:event_btnInsertMouseExited

    private void btnInsertMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertMouseReleased
        btnInsert.setBackground(new Color(0,74,163));
    }//GEN-LAST:event_btnInsertMouseReleased

    private void btnUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseEntered
        btnUpdate.setBackground(new Color(0,74,163));
    }//GEN-LAST:event_btnUpdateMouseEntered

    private void btnUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseExited
        btnUpdate.setBackground(new Color(0,74,163));
    }//GEN-LAST:event_btnUpdateMouseExited

    private void btnUpdateMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseReleased
        btnDelete.setBackground(new Color(47, 71, 194));
    }//GEN-LAST:event_btnUpdateMouseReleased

    private void btnDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseEntered
        btnDelete.setBackground(new Color(0,74,163));
    }//GEN-LAST:event_btnDeleteMouseEntered

    private void btnDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseExited
        btnDelete.setBackground(new Color(47, 71, 194));
    }//GEN-LAST:event_btnDeleteMouseExited

    private void btnDeleteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseReleased
        btnDelete.setBackground(new Color(0,74,163));
    }//GEN-LAST:event_btnDeleteMouseReleased

    private void btnResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseEntered
        btnReset.setBackground(new Color(47, 71, 194));
    }//GEN-LAST:event_btnResetMouseEntered

    private void btnResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseExited
        btnReset.setBackground(new Color(0,74,163));
    }//GEN-LAST:event_btnResetMouseExited

    private void btnResetMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseReleased
        btnReset.setBackground(new Color(0,74,163));
    }//GEN-LAST:event_btnResetMouseReleased

    private void btnDetailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetailMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDetailMouseEntered

    private void btnDetailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetailMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDetailMouseExited

    private void btnDetailMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetailMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDetailMouseReleased

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        if(cekEmptyKereta()){
            JOptionPane.showMessageDialog(this, "One or more Fields are empty!");
        } else{
            kereta = new Kereta();
            kereta.setId_kereta(txtIdkereta.getText());
            kereta.setNama_Kereta(txtNama.getText());
            kereta.setId_kelas(txtPilihKelas.getSelectedItem().toString());
            kereta.setGerbong(Integer.parseInt(txtGerbong.getText()));
            try {
                controler.insertRecord(kereta);
                show_data_to_table_kereta();
                clearFields();
            } catch (SQLException ex) {
                Logger.getLogger(petugasCardMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if(cekEmptyKereta()){
            JOptionPane.showMessageDialog(this, "One or more Fields are empty!");
        } else{
            kereta = new Kereta();
            kereta.setId_kereta(txtIdkereta.getText());
            kereta.setNama_Kereta(txtNama.getText());
            kereta.setId_kelas(txtPilihKelas.getSelectedItem().toString());
            kereta.setGerbong(Integer.parseInt(txtGerbong.getText()));
            try {
                controler.updateRecord(kereta);
                show_data_to_table_kereta();
                clearFields();
            } catch (SQLException ex) {
                Logger.getLogger(petugasCardMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tbKeretaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKeretaMouseClicked
        if(tbKereta.getSelectionModel().isSelectionEmpty()){
            System.out.println("null");
        } else{
            btnUpdate.setEnabled(true);
            btnDelete.setEnabled(true);
            btnInsert.setEnabled(false);
            txtIdkereta.setEditable(false);
            int index = tbKereta.getSelectedRow();
            show_item_in_form_kereta(index);
        }
    }//GEN-LAST:event_tbKeretaMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int result = JOptionPane.showConfirmDialog(null, 
            "Hapus data masinis "+ txtIdkereta.getText() +"?",null, JOptionPane.YES_NO_OPTION);
                if(result == JOptionPane.YES_OPTION) {
                    try {
                        controller.deleteRecord(txtIdkereta.getText());
                        show_data_to_table_kereta();
                        clearFields();
                    } catch (SQLException ex) {
                        Logger.getLogger(petugasCardMenu.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else{
                    System.out.println("Abort!");
                }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        clearFields();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnFirstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFirstMouseClicked
        pos = 0;
        show_item_in_form_kereta(pos);
        tbKereta.setRowSelectionInterval(pos, pos);
        txtIdkereta.setEditable(false);
        btnUpdate.setEnabled(true);
        btnDelete.setEnabled(true);
        btnInsert.setEnabled(false);
    }//GEN-LAST:event_btnFirstMouseClicked

    private void btnPrevMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrevMouseClicked
        if(tbKereta.getSelectionModel().isSelectionEmpty()){
            tbKereta.setRowSelectionInterval(0, 0);
        } else{
            pos = tbKereta.getSelectedRow();
            pos--;
            if(pos < 0){
                pos = 0;
            }
            tbKereta.setRowSelectionInterval(pos, pos);
        }
        show_item_in_form_kereta(pos);
        tbKereta.setRowSelectionInterval(pos, pos);
        txtIdkereta.setEditable(false);
        btnUpdate.setEnabled(true);
        btnDelete.setEnabled(true);
        btnInsert.setEnabled(false);
    }//GEN-LAST:event_btnPrevMouseClicked

    private void btnNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseClicked
        if(tbKereta.getSelectionModel().isSelectionEmpty()){
            tbKereta.setRowSelectionInterval(0, 0);
        } else{
            pos = tbKereta.getSelectedRow();
            pos++;
            if(pos >= tbKereta.getRowCount()){
                pos = tbKereta.getRowCount()-1;
            }
            tbKereta.setRowSelectionInterval(pos, pos);
        }
        show_item_in_form_kereta(pos);
        tbKereta.setRowSelectionInterval(pos, pos);
        txtIdkereta.setEditable(false);
        btnUpdate.setEnabled(true);
        btnDelete.setEnabled(true);
        btnInsert.setEnabled(false);
    }//GEN-LAST:event_btnNextMouseClicked

    private void btnLastMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLastMouseClicked
        pos = tbKereta.getRowCount()-1;
        tbKereta.setRowSelectionInterval(pos, pos);
        show_item_in_form_kereta(pos);
        txtIdkereta.setEditable(false);
        btnUpdate.setEnabled(true);
        btnDelete.setEnabled(true);
        btnInsert.setEnabled(false);
    }//GEN-LAST:event_btnLastMouseClicked

    private void show_item_in_form(int index){
        txtIdkelas.setText(tbKelas.getValueAt(index, 1).toString());
        txtNamakelas.setText(tbKelas.getValueAt(index, 2).toString());
        txtKeterangankelas.setText(tbKelas.getValueAt(index, 3).toString());
    }
    
    private void show_item_in_form_kereta(int index){
        txtIdkereta.setText(tbKereta.getValueAt(index, 1).toString());
        txtNama.setText(tbKereta.getValueAt(index, 2).toString());
        String kelas = tbKereta.getValueAt(index, 3).toString();
        int items = txtPilihKelas.getItemCount();
        for(int i=0;i<items;i++){
            if(kelas.trim().equals(txtPilihKelas.getItemAt(i))){
                txtPilihKelas.setSelectedIndex(i);
            }
        }
        txtGerbong.setText(tbKereta.getValueAt(index, 4).toString());
    }
    
    private boolean cekEmpty(){
        if(txtIdkelas.getText().isEmpty() || txtNamakelas.getText().isEmpty() || txtKeterangankelas.getText().isEmpty()){
            return true;
        } else{
            return false;
        }
    }
    
    private boolean cekEmptyKereta(){
        if(txtIdkereta.getText().isEmpty() || txtNama.getText().isEmpty() || txtGerbong.getText().isEmpty()){
            return true;
        } else{
            return false;
        }
    }
    
    private void clearFields(){
        btnInsertKelas.setEnabled(true);
        txtIdkelas.setText("");
        txtIdkelas.setEditable(true);
        txtNamakelas.setText("");
        txtKeterangankelas.setText("");
        btnUpdateKelas.setEnabled(false);
        btnDeleteKelas.setEnabled(false);
        tbKelas.getSelectionModel().clearSelection();
        
        txtIdkereta.setText("");
        txtIdkereta.setEditable(true);
        txtNama.setText("");
        txtPilihKelas.setSelectedIndex(0);
        txtGerbong.setText("");
        btnUpdate.setEnabled(true);
        btnDelete.setEnabled(true);
        tbKereta.getSelectionModel().clearSelection();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyMenuTab;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteKelas;
    private javax.swing.JButton btnDetail;
    private javax.swing.JPanel btnFirst;
    private javax.swing.JPanel btnFirstKelas;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnInsertKelas;
    private javax.swing.JPanel btnLast;
    private javax.swing.JPanel btnLastKelas;
    private javax.swing.JPanel btnMenuKelas;
    private javax.swing.JPanel btnMenuKereta;
    private javax.swing.JPanel btnNext;
    private javax.swing.JPanel btnNextKelas;
    private javax.swing.JPanel btnPrev;
    private javax.swing.JPanel btnPrevKelas;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnResetKelas;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdateKelas;
    private javax.swing.JPanel contentBodyMenuCard;
    private javax.swing.JPanel contentCardKelas;
    private javax.swing.JPanel contentCardKereta;
    private javax.swing.JPanel headerMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTable tbKelas;
    private javax.swing.JTable tbKereta;
    private javax.swing.JTextField txtGerbong;
    private javax.swing.JTextField txtIdkelas;
    private javax.swing.JTextField txtIdkereta;
    private javax.swing.JTextField txtKeterangankelas;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNamakelas;
    private javax.swing.JComboBox<String> txtPilihKelas;
    // End of variables declaration//GEN-END:variables
}
