/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dashboard.Manager;

import Dashboard.Manager.Menu.jadwalCardMenu;
import Dashboard.Manager.Menu.masinisCardMenu;
import Dashboard.Manager.Menu.petugasCardMenu;
import Dashboard.Manager.Menu.keretaCardMenu;
import java.awt.CardLayout;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Ouka
 */
public class managerDashboard extends javax.swing.JFrame {

    /**
     * Creates new form adminDashboard
     */
    private CardLayout sideMenuCard;
    private petugasCardMenu petugascard;
    private masinisCardMenu masiniscard;
    private keretaCardMenu keretacard;
    private jadwalCardMenu jadwalCard;
    public managerDashboard() throws SQLException{
        initComponents();
        petugascard = new petugasCardMenu();
        masiniscard = new masinisCardMenu();
        keretacard = new keretaCardMenu();
        jadwalCard = new jadwalCardMenu();
        sideMenuCard = (CardLayout) menuPane.getLayout();
        menuPane.add(jadwalCard, "JadwalCard");
        menuPane.add(keretacard, "KeretaCard");
        menuPane.add(masiniscard, "MasinisCard");
        menuPane.add(petugascard, "PetugasCard");
        sideMenuCard.show(menuPane, "JadwalCard");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sideMenuPane = new javax.swing.JPanel();
        dashboardIcon = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        homeButton = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jadwalButton = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        keretaButton = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        masinisButton = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        petugasButton = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        closeButton = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        headerDragPane = new javax.swing.JPanel();
        menuPane = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 710));

        jPanel1.setBackground(new java.awt.Color(0, 30, 84));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sideMenuPane.setBackground(new java.awt.Color(0, 0, 27));
        sideMenuPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashboardIcon.setBackground(new java.awt.Color(0, 0, 27));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/database_administrator_30px.png"))); // NOI18N

        javax.swing.GroupLayout dashboardIconLayout = new javax.swing.GroupLayout(dashboardIcon);
        dashboardIcon.setLayout(dashboardIconLayout);
        dashboardIconLayout.setHorizontalGroup(
            dashboardIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        dashboardIconLayout.setVerticalGroup(
            dashboardIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        sideMenuPane.add(dashboardIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        homeButton.setBackground(new java.awt.Color(0, 0, 27));
        homeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeButtonMouseClicked(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/home_30px.png"))); // NOI18N

        javax.swing.GroupLayout homeButtonLayout = new javax.swing.GroupLayout(homeButton);
        homeButton.setLayout(homeButtonLayout);
        homeButtonLayout.setHorizontalGroup(
            homeButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        homeButtonLayout.setVerticalGroup(
            homeButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        sideMenuPane.add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, -1));

        jadwalButton.setBackground(new java.awt.Color(0, 0, 27));
        jadwalButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jadwalButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jadwalButtonMouseClicked(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/calendar_plus_30px.png"))); // NOI18N

        javax.swing.GroupLayout jadwalButtonLayout = new javax.swing.GroupLayout(jadwalButton);
        jadwalButton.setLayout(jadwalButtonLayout);
        jadwalButtonLayout.setHorizontalGroup(
            jadwalButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        jadwalButtonLayout.setVerticalGroup(
            jadwalButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        sideMenuPane.add(jadwalButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 251, -1, -1));

        keretaButton.setBackground(new java.awt.Color(0, 0, 27));
        keretaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        keretaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keretaButtonMouseClicked(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/train_30px.png"))); // NOI18N

        javax.swing.GroupLayout keretaButtonLayout = new javax.swing.GroupLayout(keretaButton);
        keretaButton.setLayout(keretaButtonLayout);
        keretaButtonLayout.setHorizontalGroup(
            keretaButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        keretaButtonLayout.setVerticalGroup(
            keretaButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        sideMenuPane.add(keretaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 312, -1, -1));

        masinisButton.setBackground(new java.awt.Color(0, 0, 27));
        masinisButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        masinisButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masinisButtonMouseClicked(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/driver_30px.png"))); // NOI18N

        javax.swing.GroupLayout masinisButtonLayout = new javax.swing.GroupLayout(masinisButton);
        masinisButton.setLayout(masinisButtonLayout);
        masinisButtonLayout.setHorizontalGroup(
            masinisButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        masinisButtonLayout.setVerticalGroup(
            masinisButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        sideMenuPane.add(masinisButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 373, -1, -1));

        petugasButton.setBackground(new java.awt.Color(0, 0, 27));
        petugasButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        petugasButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                petugasButtonMouseClicked(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/reseller_30px.png"))); // NOI18N

        javax.swing.GroupLayout petugasButtonLayout = new javax.swing.GroupLayout(petugasButton);
        petugasButton.setLayout(petugasButtonLayout);
        petugasButtonLayout.setHorizontalGroup(
            petugasButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        petugasButtonLayout.setVerticalGroup(
            petugasButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        sideMenuPane.add(petugasButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 434, -1, -1));

        closeButton.setBackground(new java.awt.Color(0, 0, 27));
        closeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeButtonMouseExited(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icon/shutdown_30px.png"))); // NOI18N

        javax.swing.GroupLayout closeButtonLayout = new javax.swing.GroupLayout(closeButton);
        closeButton.setLayout(closeButtonLayout);
        closeButtonLayout.setHorizontalGroup(
            closeButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        closeButtonLayout.setVerticalGroup(
            closeButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        sideMenuPane.add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, -1, -1));

        jPanel1.add(sideMenuPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 710));

        headerDragPane.setBackground(new java.awt.Color(255, 255, 255));
        headerDragPane.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerDragPaneMouseDragged(evt);
            }
        });
        headerDragPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerDragPaneMousePressed(evt);
            }
        });

        javax.swing.GroupLayout headerDragPaneLayout = new javax.swing.GroupLayout(headerDragPane);
        headerDragPane.setLayout(headerDragPaneLayout);
        headerDragPaneLayout.setHorizontalGroup(
            headerDragPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        headerDragPaneLayout.setVerticalGroup(
            headerDragPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(headerDragPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 50));

        menuPane.setBackground(new java.awt.Color(0, 30, 84));
        menuPane.setLayout(new java.awt.CardLayout());
        jPanel1.add(menuPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 1140, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private int xAxis, yAxis;
    private void headerDragPaneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerDragPaneMousePressed
        xAxis = evt.getX();
        yAxis = evt.getY();
    }//GEN-LAST:event_headerDragPaneMousePressed

    private void headerDragPaneMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerDragPaneMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(x-xAxis, y-yAxis);
    }//GEN-LAST:event_headerDragPaneMouseDragged

    private void homeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMouseClicked
        homeButton.setBackground(new Color(45,45,45));
        jadwalButton.setBackground(new Color(0,0,27));
        keretaButton.setBackground(new Color(0,0,27));
        masinisButton.setBackground(new Color(0,0,27));
        petugasButton.setBackground(new Color(0,0,27));
    }//GEN-LAST:event_homeButtonMouseClicked

    private void jadwalButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jadwalButtonMouseClicked
        homeButton.setBackground(new Color(0,0,27));
        jadwalButton.setBackground(new Color(45,45,45));
        keretaButton.setBackground(new Color(0,0,27));
        masinisButton.setBackground(new Color(0,0,27));
        petugasButton.setBackground(new Color(0,0,27));
        sideMenuCard.show(menuPane, "JadwalCard");
        try {
            jadwalCard.showList();
        } catch (SQLException ex) {
            Logger.getLogger(managerDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jadwalButtonMouseClicked

    private void keretaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keretaButtonMouseClicked
        homeButton.setBackground(new Color(0,0,27));
        jadwalButton.setBackground(new Color(0,0,27));
        keretaButton.setBackground(new Color(45,45,45));
        masinisButton.setBackground(new Color(0,0,27));
        petugasButton.setBackground(new Color(0,0,27));
        sideMenuCard.show(menuPane, "KeretaCard");
    }//GEN-LAST:event_keretaButtonMouseClicked

    private void masinisButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masinisButtonMouseClicked
        homeButton.setBackground(new Color(0,0,27));
        jadwalButton.setBackground(new Color(0,0,27));
        keretaButton.setBackground(new Color(0,0,27));
        masinisButton.setBackground(new Color(45,45,45));
        petugasButton.setBackground(new Color(0,0,27));
        sideMenuCard.show(menuPane, "MasinisCard");
    }//GEN-LAST:event_masinisButtonMouseClicked

    private void petugasButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_petugasButtonMouseClicked
        homeButton.setBackground(new Color(0,0,27));
        jadwalButton.setBackground(new Color(0,0,27));
        keretaButton.setBackground(new Color(0,0,27));
        masinisButton.setBackground(new Color(0,0,27));
        petugasButton.setBackground(new Color(45,45,45));
        sideMenuCard.show(menuPane, "PetugasCard");
    }//GEN-LAST:event_petugasButtonMouseClicked

    private void closeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseEntered
        closeButton.setBackground(new Color(214, 62, 90));
    }//GEN-LAST:event_closeButtonMouseEntered

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeButtonMouseClicked

    private void closeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseExited
        closeButton.setBackground(new Color(0,0,27));
    }//GEN-LAST:event_closeButtonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(managerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(managerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(managerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(managerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new managerDashboard().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(managerDashboard.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    public masinisCardMenu getMenuMasinis(){
        return masiniscard;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel closeButton;
    private javax.swing.JPanel dashboardIcon;
    private javax.swing.JPanel headerDragPane;
    private javax.swing.JPanel homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jadwalButton;
    private javax.swing.JPanel keretaButton;
    private javax.swing.JPanel masinisButton;
    private javax.swing.JPanel menuPane;
    private javax.swing.JPanel petugasButton;
    private javax.swing.JPanel sideMenuPane;
    // End of variables declaration//GEN-END:variables
}
